# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 88fff613d04a03e1518dce8d52378201d7ccd49505e471e5a98bb92e9e403698ea3737b21c261f8f5aaccfa1c36c4af32b23c40edbcd5cc24bdff4897f40db4b

test:
  secret_key_base: 1ddbc8df66db0ecb8fffd4ce718277048a6b3a5bfafd8a4450595de07e8fd8e54d9505522d5e0e2d252fd6d0dda2b52fefe9472ac55d3e6fa1dad9c9b97d2b38

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
